### ISSUE TITLE
关于GSI

### ISSUE THREAD

**Issue by TimsFong** [kindle4jerry/kindle4jerry#1]
我正在下载这里的GSI https://sourceforge.net/projects/kindle4jerry-rom/files/KirinGSI/ ，因为文件名标识不是很清楚，你在telegram有账号吗？只是想方便请教你。比如：p20/p21是指A13/A14吗？
另外。如果你构建的是phhGSI。可以到这里发布：https://github.com/phhusson/treble_experimentations/wiki/Generic-System-Image-%28GSI%29-list 
phhGSI群组：https://t.me/phhtreble

**Comment by kindle4jerry** [comment]
很高兴看见熟悉的id，我在Xda的id是Dispossible。
我更新了readme.txt，里面包括说明以及安卓版本，可以对照一下[https://sourceforge.net/projects/kindle4jerry-rom/files/KirinGSI/](url)
已经不维护了，针对华为机型GSI有一些特殊的补丁我扔到这个项目里了，有需求可以自取，现在应该有别人在做华为gsi应该[https://github.com/kindle4jerry/patches_kindle4jerry](url)
