### ISSUE TITLE
Lineage OS nubia维护

### ISSUE THREAD

**Issue by TimsFong** [kindle4jerry/kindle4jerry#2]
大佬：lineage OS Nubia的维护应该也是你，请问你放弃了维护吗？发现所有你维护的nubia都已拉下。谢谢。

**Comment by kindle4jerry** [comment]
你应该仔细看lineageos开源项目，[https://github.com/LineageOS/android_device_nubia_nx563j](url)，并且注意到[https://github.com/Cyborg2017](url)这才是维护nubia一堆机型的大佬，他现在已经把所有nubia设备出掉了并且不再维护了，如果你有兴趣你可以尝试接手。

**Comment by TimsFong** [comment]
我根本就不懂，哈哈哈。会有人接手吗？比如：你这样的大佬，才有可能接手。
